default_platform(:android)

platform :android do

  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do

    sh("cd ../../../pokemon_tcg && flutter clean")
    sh("cd ../../../pokemon_tcg && flutter pub get")
    sh("cd ../../../pokemon_tcg && flutter build apk --release")


    firebase_app_distribution(
      apk_path: sh("pwd | tr -d '\n'").concat("/app-release.apk"),
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      testers: "llanta.jeremy@gmail.com"
      release_notes: "Git commit: #{last_git_commit[:abbreviated_commit_hash]}",
    )
  end
end